api_platform:
    title: ClubScheduler API
    version: 1.0.0
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
        html: ["text/html"]
    docs_formats:
        jsonopenapi: ["application/vnd.openapi+json"]
        json: ["application/vnd.openapi+json"]
        jsonld: ["application/ld+json"]
        html: ["text/html"]
    error_formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
