framework:
    messenger:
        transports:
            async: "%env(MESSENGER_TRANSPORT_DSN)%"

        routing:
            App\Message\GenerateScheduleMessage: async
            App\Message\ExportPdfMessage: async
