symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    # Token lifetime (default 1h) and throttling (min delay between requests per user).
    lifetime: 3600
    throttle_limit: 3600
