framework:
    cache:
        app: cache.adapter.array
        pools:
            cache.tenant:
                adapter: cache.adapter.array
            cache.schedule:
                adapter: cache.adapter.array
