<?php

declare(strict_types=1);

namespace App\Enum;

enum ImplicitConstraint: string
{
    case VENUE_AT_MOST_ONE = 'VENUE_AT_MOST_ONE';
    case COACH_NO_OVERLAP = 'COACH_NO_OVERLAP';
    case COACH_PLAYER_NO_OVERLAP = 'COACH_PLAYER_NO_OVERLAP';
    case TEAM_NO_OVERLAP = 'TEAM_NO_OVERLAP';
    case MIN_SESSIONS = 'MIN_SESSIONS';
    case ONE_SESSION_PER_DAY = 'ONE_SESSION_PER_DAY';
    case COACH_REST_DAY = 'COACH_REST_DAY';
    case SALARIE_DISTRIBUTION = 'SALARIE_DISTRIBUTION';
    case MAX_CONSECUTIVE_SESSIONS = 'MAX_CONSECUTIVE_SESSIONS';
    case AGE_ASCENDING = 'AGE_ASCENDING';
    case TRAVEL_FEASIBILITY = 'TRAVEL_FEASIBILITY';
    case REQUIRED_BRIDGE = 'REQUIRED_BRIDGE';
}
